### ISSUE TITLE
No clear way to differentiate variables instantiated in config file from local variables

### ISSUE THREAD

**Issue by AdamSturge** [JonnyLomond/FlailingCanary#4]
I think we should have an easy way to tell if a variable is defined in the config file. This makes it easier to read other peoples code. 

Some possible implementations:
- Use all caps for variable names in config file
- Append a set prefix string to variable name
- Put all config variables in a dictionary called config. Ex.) config["access token"]

**Comment by JonnyLomond** [comment]
All variables instantiated in config file are attributes of config. So they
should always be called as config.access_token, for example. Is this enough?

**Comment by AdamSturge** [comment]
ah, then yes that's fine
